"""Change sql

Revision ID: 15dd42cc4f76
Revises: b7a1931d4f0b
Create Date: 2023-11-11 06:38:00.553190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15dd42cc4f76'
down_revision: Union[str, None] = 'b7a1931d4f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('icon', 'icon', ['icon'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
